config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "pages#home"
  get "about", to: "pages#about", as: :about
  get "contact", to: "pages#contact", as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
    end 

    def about 
    end

    def contact 
        @members = ['Messi', 'Ronaldo', 'Beckham', 'Drogba', 'Luqman']

        if params[:player]
            @members = @members.select {|member| member.start_with?(params[:player])}
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Houston we have liftoff...</h1>

app/views/pages/contact.html.erb
<h2> Meet our team </h2>
<ol>
    <% @members.each do |member| %>
        <li><%= member.capitalize %> </li>
    <% end %>
<ol>

<form action="/contact" method="get">
    <input type="text" name="player" placeholder="Who are you looking for?">
    <input type="submit">
</form>

app/views/pages/home.html.erb
<%= link_to "Know more about us", about_path %>
<%= link_to "Meet our team", contact_path %>